baseURL = "https://www.gokhanmankara.com"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Gökhan MANKARA"
theme = "github.com/lxndrblz/anatole"
#disqusShortname = "gokhanblog"
googleAnalytics = "UA-10446851-2"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "category"
  archive = "archive"

[author]
  name = "Gökhan MANKARA"
  bio = "Golang, Python, Blogger, Linux Fan"
  job = "Software Developer"
  location = "Turkey/Istanbul"

[params]
  dateFormat = "2006, Jan 02"
  listDateFormat = "2006, Jan 02"


  description = "Blog - Açık Kaynak Kodlu Uygulamalar - Linux Dökümanları"
  profilePicture = "images/cover.jpg"

  favicon = "favicon/"
  reversepagetitle = true

[[params.socialIcons]]
  icon = "fab fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/gokhanmankara/"

[[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/gokhanm"
[[params.socialIcons]]
  icon = "fas fa-envelope"
  title = "e-mail"
  url = "mailto:gokhanm@gmail.com"
[[params.socialIcons]]
  icon = "fas fa-rss"
  title = "rss"
  url = "/index.xml"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "posts"
  name = "Posts"
  url = "/post"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "about"
  name = "About"
  url = "/about"

